In [ ]:
#Loading of necessary packages
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.io import arff
import io
import random
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import math
import itertools
import seaborn as sns
from time import time
from collections import OrderedDict
%matplotlib inline
gt0 = time()

In [ ]:
# Importing and Reading our data from csv file 
from google.colab import files
datasetTrain = files.upload()
datasetTest = files.upload()
# Reading the dataset from Colab Local Repository
datasetTrain = pd.read_csv('UNSW_NB15_training-set.csv')
datasetTest = pd.read_csv('UNSW_NB15_testing-set.csv')

Saving UNSW_NB15_training-set.csv to UNSW_NB15_training-set.csv

Saving UNSW_NB15_testing-set.csv to UNSW_NB15_testing-set.csv

In [ ]:
col_names = ["dur","proto","service","state","spkts","dpkts","sbytes","dbytes","rate","sttl","dttl",
              "sload","dload","sloss","dloss","sinpkt","dinpkt","sjit","djit","swin","stcpb","dtcpb","dwin",
              "tcprtt","synack","ackdat","smean","dmean","trans_depth","response_body_len","ct_srv_src",
              "ct_state_ttl","ct_dst_ltm","ct_src_dport_ltm","ct_dst_sport_ltm","ct_dst_src_ltm","is_ftp_login",
              "ct_ftp_cmd","ct_flw_http_mthd","ct_src_ltm","ct_srv_dst","is_sm_ips_ports","attack_cat","label"]

In [ ]:
datasetTrain = pd.read_csv('UNSW_NB15_training-set.csv', header=None, names = col_names)
datasetTest = pd.read_csv('UNSW_NB15_testing-set.csv', header=None, names = col_names)
print('Dimensions of the Training set:',datasetTrain.shape)
print('Dimensions of the Test set:',datasetTest.shape)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,1,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,44) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Dimensions of the Training set: (82333, 44)
Dimensions of the Test set: (175342, 44)

In [ ]:
datasetTrain.head(5)

         dur  proto  service  ...  is_sm_ips_ports  attack_cat  label
id       dur  proto  service  ...  is_sm_ips_ports  attack_cat  label
1   0.000011    udp        -  ...                0      Normal      0
2   0.000008    udp        -  ...                0      Normal      0
3   0.000005    udp        -  ...                0      Normal      0
4   0.000006    udp        -  ...                0      Normal      0

[5 rows x 44 columns]

In [ ]:
print('Training set:')
for col_name in datasetTrain.columns:
    if datasetTrain[col_name].dtypes == 'object' :
        unique_cat = len(datasetTrain[col_name].unique())
        print("Feature '{col_name}' has {unique_cat} categories".format(col_name=col_name, unique_cat=unique_cat))

print()
print('Distribution of categories in service:')
print(datasetTrain['service'].value_counts().sort_values(ascending=False).head())

Training set:
Feature 'dur' has 40009 categories
Feature 'proto' has 132 categories
Feature 'service' has 14 categories
Feature 'state' has 8 categories
Feature 'spkts' has 556 categories
Feature 'dpkts' has 582 categories
Feature 'sbytes' has 5542 categories
Feature 'dbytes' has 4963 categories
Feature 'rate' has 40671 categories
Feature 'sttl' has 16 categories
Feature 'dttl' has 12 categories
Feature 'sload' has 43055 categories
Feature 'dload' has 40632 categories
Feature 'sloss' has 360 categories
Feature 'dloss' has 441 categories
Feature 'sinpkt' has 40046 categories
Feature 'dinpkt' has 37655 categories
Feature 'sjit' has 39946 categories
Feature 'djit' has 38386 categories
Feature 'swin' has 14 categories
Feature 'stcpb' has 39221 categories
Feature 'dtcpb' has 39110 categories
Feature 'dwin' has 17 categories
Feature 'tcprtt' has 26640 categories
Feature 'synack' has 25750 categories
Feature 'ackdat' has 25063 categories
Feature 'smean' has 2058 categories
Feature 'dmean' has 1942 categories
Feature 'trans_depth' has 12 categories
Feature 'response_body_len' has 1447 categories
Feature 'ct_srv_src' has 111 categories
Feature 'ct_state_ttl' has 14 categories
Feature 'ct_dst_ltm' has 97 categories
Feature 'ct_src_dport_ltm' has 94 categories
Feature 'ct_dst_sport_ltm' has 59 categories
Feature 'ct_dst_src_ltm' has 110 categories
Feature 'is_ftp_login' has 6 categories
Feature 'ct_ftp_cmd' has 7 categories
Feature 'ct_flw_http_mthd' has 15 categories
Feature 'ct_src_ltm' has 97 categories
Feature 'ct_srv_dst' has 110 categories
Feature 'is_sm_ips_ports' has 5 categories
Feature 'attack_cat' has 11 categories
Feature 'label' has 5 categories

Distribution of categories in service:
-       47153
dns     21367
http     8287
smtp     1851
ftp      1552
Name: service, dtype: int64

In [ ]:
print('Label distribution Training set, attack_cat:')
print(datasetTrain['attack_cat'].value_counts())
print()
print('Label distribution Test set:')
print(datasetTest['attack_cat'].value_counts())

Label distribution Training set, attack_cat:
Normal            37000
Generic           18871
Exploits          11132
Fuzzers            6062
DoS                4089
Reconnaissance     3496
Analysis            677
Backdoor            583
Shellcode           378
Worms                44
attack_cat            1
Name: attack_cat, dtype: int64

Label distribution Test set:
Normal            56000
Generic           40000
Exploits          33393
Fuzzers           18184
DoS               12264
Reconnaissance    10491
Analysis           2000
Backdoor           1746
Shellcode          1133
Worms               130
attack_cat            1
Name: attack_cat, dtype: int64